[package]
name = "mirror-sync"
version = "0.1.0"
authors = ["Jordan Miner <jminer7@gmail.com>"]

[dependencies]
clear-coat = {path = "../clear-coat"}
crossbeam = "0.2"
itertools = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
